# Generated by Django 5.0.3 on 2025-05-10 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Soldier',
            fields=[
                ('devEui', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='ID пристрою')),
                ('first_name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=100, verbose_name='Прізвище')),
                ('unit', models.CharField(max_length=200, verbose_name='Підрозділ')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Останнє оновлення')),
            ],
            options={
                'verbose_name': 'Солдат',
                'verbose_name_plural': 'Солдати',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='MedicalData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('spo2', models.IntegerField(verbose_name='SPO2')),
                ('heart_rate', models.IntegerField(verbose_name='Пульс')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Довгота')),
                ('timestamp', models.DateTimeField(verbose_name='Час виміру')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.soldier', verbose_name='Пристрій')),
            ],
            options={
                'verbose_name': 'Медичні дані',
                'verbose_name_plural': 'Медичні дані',
                'ordering': ['-timestamp'],
            },
        ),
    ]
