# Generated by Django 5.0.3 on 2025-05-12 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soldier',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Поранений', 'verbose_name_plural': 'Поранені'},
        ),
        migrations.AddField(
            model_name='medicaldata',
            name='issue_type',
            field=models.CharField(choices=[('SPO2', 'Критичний SpO2'), ('HR', 'Критичний пульс'), ('BOTH', 'Критичні SpO2 та пульс'), ('SENSOR_ERROR', 'Помилка датчиків'), ('NORMAL', 'Показники в нормі')], default='NORMAL', max_length=20, verbose_name='Тип проблеми'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='evacuation_started',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Час початку евакуації'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='evacuation_status',
            field=models.CharField(choices=[('NOT_NEEDED', 'Евакуація не потрібна'), ('NEEDED', 'Потребує евакуації'), ('IN_PROGRESS', 'В процесі евакуації'), ('EVACUATED', 'Евакуйований')], default='NEEDED', max_length=20, verbose_name='Статус евакуації'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='evacuation_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Час евакуації'),
        ),
    ]
