# Generated by Django 5.0.3 on 2025-05-14 20:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soldier',
            name='evacuation_started',
        ),
        migrations.RemoveField(
            model_name='soldier',
            name='evacuation_status',
        ),
        migrations.RemoveField(
            model_name='soldier',
            name='evacuation_time',
        ),
        migrations.AddField(
            model_name='alert',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Час прочитання'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Створено'),
        ),
        migrations.CreateModel(
            name='Evacuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_NEEDED', 'Евакуація не потрібна'), ('NEEDED', 'Потребує евакуації'), ('IN_PROGRESS', 'В процесі евакуації'), ('EVACUATED', 'Евакуйований')], default='NEEDED', max_length=20, verbose_name='Статус евакуації')),
                ('evacuation_time', models.DateTimeField(blank=True, null=True, verbose_name='Час евакуації')),
                ('evacuation_started', models.DateTimeField(blank=True, null=True, verbose_name='Час початку евакуації')),
                ('evacuation_team', models.CharField(blank=True, max_length=200, null=True, verbose_name='Евакуаційна команда')),
                ('priority', models.IntegerField(default=0, verbose_name='Пріоритет евакуації')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примітки')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Останнє оновлення')),
                ('soldier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evacuation', to='api.soldier', verbose_name='Поранений')),
            ],
            options={
                'verbose_name': 'Евакуація',
                'verbose_name_plural': 'Евакуації',
                'ordering': ['priority', 'evacuation_started'],
            },
        ),
    ]
