# Generated by Django 5.0.3 on 2025-05-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_soldier_evacuation_started_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='joinEui',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Join EUI (EUI64)'),
        ),
    ]
