# Generated by Django 5.0.3 on 2025-05-16 17:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_soldier_joineui'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soldier',
            name='joinEui',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Адміністратор'), ('MEDICAL_STAFF', 'Медичний персонал'), ('EVACUATION_TEAM', 'Евакуаційна команда'), ('ANALYST', 'Аналітик'), ('VIEWER', 'Переглядач')], default='VIEWER', max_length=20, verbose_name='Роль користувача')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер телефону')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Посада')),
                ('unit', models.CharField(blank=True, max_length=100, null=True, verbose_name='Підрозділ')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Остання активність')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Створено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профіль користувача',
                'verbose_name_plural': 'Профілі користувачів',
                'ordering': ['user__username'],
            },
        ),
    ]
